## https://www.appveyor.com/docs/appveyor-yml/
#image: Visual Studio 2022
image: Ubuntu2004
version: 1.0.{build}

configuration:
- Debug

platform: Any CPU

pull_requests:  
  do_not_increment_build_number: false
  
# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true  

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  JAVA_HOME: C:\Program Files\Java\jdk15
  SHOPPINGCART_API_TOKEN:
    secure: EQT+mZIVdiZT+nP78HyRuYDYvqVseBohm6Q4vBBkZMnSj/itnOpPfBZIUXonfBsJ
  SHOPPINGCART_WEB_TOKEN:
    secure: xC1fiMQ8OPKK5kd4EYHDH05yl2S5yeiRyJSo1RhzBFB3GoUrGzRlNkucqWEiNSK7
  IDENTITYSERVER6_TOKEN:
    secure: SEgGxXS0/X4CQmy72WIUSZLhgjoYZaES9UFyWQE/SPqnNv33XJjhFIh6ksXHHK7z
  POLICYSERVER_TOKEN:
    secure: JgrMEuJlbBSM3SPoTPNL9v7e725M7/l3e9DLe6kHT9giL7japwBFykmqbyABZvLj
  BUILDKIT_PROGRESS: plain
  DOCKER_USER: corts
  DOCKER_PASS:
    secure: 0rxw6OrmXRqB3UuBZFbC/w==

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: Get-ChildItem "Env:"
- ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
- dotnet --info

build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true 
  include_nuget_references: true
  verbosity: minimal

build_script:
- ps: appveyor-build.ps1

cache:
- '%USERPROFILE%\.nuget\packages'
  
nuget:
  disable_publish_on_pr: true
 
