## https://www.appveyor.com/docs/appveyor-yml/
#image: Visual Studio 2022
image: Ubuntu2004
version: 1.0.{build}

configuration:
- Debug

platform: Any CPU

pull_requests:  
  do_not_increment_build_number: true

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  JAVA_HOME: C:\Program Files\Java\jdk15
  SONAR_TOKEN:
    secure: EQT+mZIVdiZT+nP78HyRuYDYvqVseBohm6Q4vBBkZMnSj/itnOpPfBZIUXonfBsJ
  BUILDKIT_PROGRESS: plain
  DOCKER_USER: corts
  DOCKER_PASS:
    secure: 0rxw6OrmXRqB3UuBZFbC/w==

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
- ps: Get-ChildItem "Env:"
- ps: docker login -u="$env:DOCKER_USER" -p="$env:DOCKER_PASS"

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

before_build:
- set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
- dotnet --info

build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true 
  include_nuget_references: true
  verbosity: minimal

build_script:
- ps: >-
    $buildNumber = $env:APPVEYOR_BUILD_NUMBER;
    $branch = $env:APPVEYOR_REPO_BRANCH;
    cd shoppingcart-api;
    .\build-dockerimages.ps1 -branch $branch -buildCounter $buildNumber;
    cd ..;
    cd shoppingcart-web;
    .\build-dockerimages.ps1 -branch $branch -buildCounter $buildNumber;
    cd ..;
    cd identityServer6;
    .\build-dockerimages.ps1 -branch $branch -buildCounter $buildNumber;
    cd ..;
    cd policyserver;
    .\build-dockerimages.ps1 -branch $branch -buildCounter $buildNumber;
    #-pushImage -systemprune
    cd ..;
    echo "building version $version from branch $branch targeting $target with analysis arguments of $analysisArgs";

cache:
- '%USERPROFILE%\.nuget\packages'
  
nuget:
  disable_publish_on_pr: true
 
