services:
#5005 - healthmonitor-api
#5002 - identityserver
#5001 - policyserver
#5007 - mockserver
#5000 - shoppingcart-api
#4200 - shoppingcart-web
#5003 - dashboard-web
#5006 - sqlreport-api
  rabbitmq:
    environment:
      ACCEPT_EULA: "Y"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  seq:
    environment:
      ACCEPT_EULA: "Y"
    image: datalust/seq:latest
    restart: unless-stopped
    ports:
      - 5341:80
  redis:
    image: redislabs/redismod
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379
  healthmonitor-api:
    image: cortside/healthmonitor-api:develop
    restart: unless-stopped
    ports:
      - 5005:5000
    volumes:
      - coeus-data:/settings
    healthcheck:
      test: curl --fail http://localhost:5000/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s      
  identityserver-bootstrap:
    image: cortside/identityserver4:develop
    depends_on:
      db:
        condition: "service_healthy"
    volumes:
      - coeus-data:/settings
    command: ["/bin/sh", "-c", "cd /sql; pwsh ./update-database.ps1 -CreateDatabase -TestData -appsettings /settings/identityserver/appsettings.local.json"]
  identityserver:
    image: cortside/identityserver4:develop
    restart: unless-stopped
    ports:
      - 5002:5000
    depends_on:
      - db
      - identityserver-bootstrap
    volumes:
      - coeus-data:/settings
    healthcheck:
      test: curl --fail http://localhost:5000/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s      
  policyserver:
    image: cortside/policyserver:develop
    restart: unless-stopped
    ports:
      - 5001:5001
    depends_on:
      - db
      - identityserver
    volumes:
      - coeus-data:/settings
    healthcheck:
      test: curl --fail http://localhost:5001/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s      
  mockserver:
    image: cortside/policyserver:develop
    restart: unless-stopped
    environment:
      SERVICE_NAME: mockserver
    ports:
      - 5007:5001
    depends_on:
      - db
      - identityserver
    volumes:
      - coeus-data:/settings
    healthcheck:
      test: curl --fail http://localhost:5001/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s      
  shoppingcart-bootstrap:
    image: cortside/shoppingcart-api:develop
    depends_on:
      db:
        condition: "service_healthy"
    volumes:
      - coeus-data:/settings
    command: ["/bin/sh", "-c", "cd /sql; pwsh ./update-database.ps1 -CreateDatabase -appsettings /settings/shoppingcart-api/appsettings.local.json"]   
  shoppingcart-api:
    image: cortside/shoppingcart-api:develop
    restart: unless-stopped
    ports:
      - 5000:5000
    depends_on:
      - db
      - mockserver
      - identityserver
      - shoppingcart-bootstrap
    volumes:
      - coeus-data:/settings
    healthcheck:
      test: curl --fail http://localhost:5000/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s      
  sqlreport-bootstrap:
    image: cortside/sqlreport-api:develop
    depends_on:
      db:
        condition: "service_healthy"
    volumes:
      - coeus-data:/settings
    command: ["/bin/sh", "-c", "cd /sql; pwsh ./update-database.ps1 -CreateDatabase -appsettings /settings/sqlreport-api/app/appsettings.local.json"]   
  sqlreport-api:
    image: cortside/sqlreport-api:develop
    restart: unless-stopped
    ports:
      - 5006:5000
    depends_on:
      - db
      - mockserver
      - identityserver
      - sqlreport-bootstrap
    volumes:
      - coeus-data:/settings
    healthcheck:
      test: curl --fail http://localhost:5000/api/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s      
  shoppingcart-web:
    image: cortside/shoppingcart-web:develop
    restart: unless-stopped
    ports:
      - 5004:8080
    depends_on:
      - shoppingcart-api
    volumes:
      - coeus-data:/settings
    environment:
      EXTERNAL_HOST: ${DOCKER_HOST}
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s      
  dashboard-web:
    image: cortside/dashboard-web:develop
    restart: unless-stopped
    ports:
      - 5003:8080
    depends_on:
      - identityserver
    volumes:
      - coeus-data:/settings
    environment:
      EXTERNAL_HOST: ${DOCKER_HOST}
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s      
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "password1@"
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    ports:
      - 1434:1433
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P password1@ -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s     
volumes:
  coeus-data:
    external: true
