services:
#5002 - ids
#5001 - policyserver
#5000 - shoppingcart-api
#4200 - shoppingcart-web
  identityserver:
    image: cortside/identityserver6:develop
    ports:
      - 5002:5000
  policyserver:
    image: cortside/policyserver:develop
    ports:
      - 5001:5000
  db:
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: password1@
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P password1@ -Q 'SELECT 1' || exit 1"]
        interval: 10s
        retries: 10
        start_period: 10s
        timeout: 3s     
         
       