apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mcp
resources:
- namespace.yaml
- secret.yaml
- deploy-app.yaml
- svc-app.yaml
- config-otel.yaml
- deploy-otel.yaml
- svc-otel.yaml
- config-prometheus.yaml
- deploy-prometheus.yaml
- svc-prometheus.yaml
- config-grafana-datasources.yaml
- config-grafana-dashboards.yaml
- deploy-grafana.yaml
- svc-grafana.yaml
