image: Visual Studio 2019
version: 1.0.{build}

configuration:
- Debug

#platform: Any CPU

environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

init:
- ps: $Env:LABEL = "CI" + $Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")

assembly_info:
  patch: true
  file: '**\Assembly*Info.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
  
dotnet_csproj: 
  patch: true 
  file: '**\*.csproj' 
  version: '{version}' 
  assembly_version: '{version}' 
  file_version: '{version}'  

before_build:
  - appveyor-retry dotnet restore src -v Minimal
  - set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

build_script:
- ps: ./build.ps1

artifacts:
  - path: artifacts\**\*.*

cache:
  - '%USERPROFILE%\.nuget\packages'
  
nuget:
  disable_publish_on_pr: true
  
test:
  assemblies:

deploy:
- provider: NuGet
  api_key:
    secure: ObtpuUmk0xC2aZ3+pVBY1xARi6fM7LdzNqot5Cr8Iwoitol4oElmDnU9SNGkD+3w
