const colors = require('tailwindcss/colors');

module.exports = {
    content: ['./src/**/*.{html,ts}'],
    darkMode: false, // or 'media' or 'class'
    theme: {
        fontFamily: {
            sans: ['Roboto', 'ui-sans-serif', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Helvetica Neue', 'Arial', 'Noto Sans', 'sans-serif'],
        },
        screens: {
            sm: '576px',
            md: '768px',
            lg: '992px',
            xl: '1200px',
            '2xl': '1400px',
        },
        colors: {
            transparent: 'transparent',
            current: 'currentColor',
            black: 'var(--color-black)',
            white: 'var(--color-white)',
            primary: 'var(--color-primary)',
            secondary: 'var(--color-secondary)',
            success: 'var(--color-success)',
            warning: 'var(--color-warning)',
            danger: 'var(--color-danger)',
            gray: {
                50: 'var(--color-gray-50)',
                100: 'var(--color-gray-100)',
                200: 'var(--color-gray-200)',
                300: 'var(--color-gray-300)',
                400: 'var(--color-gray-400)',
                500: 'var(--color-gray-500)',
                600: 'var(--color-gray-600)',
                700: 'var(--color-gray-700)',
                800: 'var(--color-gray-800)',
                900: 'var(--color-gray-900)',
                950: 'var(--color-gray-950)',
            },
            red: {
                50: 'var(--color-red-50)',
                100: 'var(--color-red-100)',
                200: 'var(--color-red-200)',
                300: 'var(--color-red-300)',
                400: 'var(--color-red-400)',
                500: 'var(--color-red-500)',
                600: 'var(--color-red-600)',
                700: 'var(--color-red-700)',
                800: 'var(--color-red-800)',
                900: 'var(--color-red-900)',
                950: 'var(--color-red-950)',
            },
            yellow: {
                50: 'var(--color-yellow-50)',
                100: 'var(--color-yellow-100)',
                200: 'var(--color-yellow-200)',
                300: 'var(--color-yellow-300)',
                400: 'var(--color-yellow-400)',
                500: 'var(--color-yellow-500)',
                600: 'var(--color-yellow-600)',
                700: 'var(--color-yellow-700)',
                800: 'var(--color-yellow-800)',
                900: 'var(--color-yellow-900)',
                950: 'var(--color-yellow-950)',
            },
            green: {
                50: 'var(--color-green-50)',
                100: 'var(--color-green-100)',
                200: 'var(--color-green-200)',
                300: 'var(--color-green-300)',
                400: 'var(--color-green-400)',
                500: 'var(--color-green-500)',
                600: 'var(--color-green-600)',
                700: 'var(--color-green-700)',
                800: 'var(--color-green-800)',
                900: 'var(--color-green-900)',
                950: 'var(--color-green-950)',
            },
            blue: {
                50: 'var(--color-blue-50)',
                100: 'var(--color-blue-100)',
                200: 'var(--color-blue-200)',
                300: 'var(--color-blue-300)',
                400: 'var(--color-blue-400)',
                500: 'var(--color-blue-500)',
                600: 'var(--color-blue-600)',
                700: 'var(--color-blue-700)',
                800: 'var(--color-blue-800)',
                900: 'var(--color-blue-900)',
                950: 'var(--color-blue-950)',
            }
        },
        extend: {},
    },
    variants: {
        extend: {},
    },
    plugins: [require('@tailwindcss/forms')],
};
